version: "2"
services:
   namenode:
      image: apache/hadoop:3
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./hadoop_config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      volumes:
        - ./data:/opt/data
   datanode:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      env_file:
        - ./hadoop_config
      environment:
          HADOOP_DATANODE_OPTS: "-Xmx20g"
   resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./hadoop_config
      volumes:
        - ./test.sh:/opt/test.sh
   nodemanager:
      image: apache/hadoop:3
      command: ["yarn", "nodemanager"]
      env_file:
        - ./hadoop_config
   datanode2:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      env_file:
        - ./hadoop_config
      environment:
          HADOOP_DATANODE_OPTS: "-Xmx20g"
   datanode3:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      env_file:
        - ./hadoop_config
      environment:
          HADOOP_DATANODE_OPTS: "-Xmx20g"